EndTime=Fri Sep 28 07:35:35 UTC 2012
StartTime=1348817734.228
Time=1246 msecs
Hostname=cde-gamma-na-6001.iad6.amazon.com
Timing=KindleMutualAuthenticator.authenticateRequest:176/1,DeviceMasterCacheService.GetRegisteredDeviceAccounts:336/2,DeviceMasterDataLoader.constructor:160/1,DeviceMetadataServiceDataLoader.constructor:28/2,DeviceMetadataService.GetDeviceMetadata:14/1,FionaCDEServiceEngine.Weblab:0/1,SidecarStream.AnnotationLoader:895/1,SidecarStream.request:895/1,SidecarStream.request.noStream:895/1,SidecarStream.request.generate.sidecar:895/1,AvailabilityAnalyzerLoadShedder.ShouldShed:0/1,LoadShedderProtector.UDLMetadataServiceFacade.readMetadata.Time:26/1,UDLMetadataService.readMetadata:26/1,AnnotationLoader.makeGetAnnotationsQuery:167/1,DigitalAnnotationsService.getAnnotations:167/1,AnnotationLoader.makeGetAnnotationsQuery.SUCCESS:0/1,AnnotationLoader.FilteringTime:1/1,FutureSoftwareVersionService.getResult:0/1,ContentMetadata.call:21/1,PositionMapper.call:69/1,CodigoDigicat.getResult:11/2,KCMS.getMetadata:10/1,KCMS.getManifest:14/1,DASAssetLoader.loadAsset:462/2,DASAssetLoader.getSimpleFileStorage:62/2,DASAssetLoader.loadAsset.getAsset:400/2,GetInstructionAndDescriptor:191/2,GetAsset.InputStream:209/2
Counters=Capabilities.CacheHit=1 occurence,DeviceMasterCacheService.GetRegisteredDeviceAccounts.success=1 count,AuthPool.Amazon=1 times,CertificateType.1=1 times,CustomerIdPresentA1VC38T7YXB528=1 count,DeviceMasterCacheService.GetRegisteredDeviceAccounts.success=1 count,DMCS_FoundAccount=1 occurence,DeviceMetadataService.GetDeviceMetadata.success=1 count,SidecarStream.currentCountryCodeReadFromURL=1 occurence,cde.weblab.SIDECAR_MIGRATION_CDE_14114.C=1 occurrence,SidecarStream.request.secure=1 request,RequestRate.UDLMetadataServiceFacade.readMetadataLOW=0 rate,RequestRate.UDLMetadataServiceFacade.readMetadataNORMAL=0 rate,RequestRate.UDLMetadataServiceFacade.readMetadataHIGH=0 rate,RequestRate.UDLMetadataServiceFacade.readMetadataHIGHER=0 rate,RequestRate.UDLMetadataServiceFacade.readMetadataHIGHEST=0 rate,RequestRate.UDLMetadataServiceFacade.readMetadata=0 rate,FilterRate.UDLMetadataServiceFacade.readMetadata=0 rate,FailureRate.UDLMetadataServiceFacade.readMetadata=0 rate,UDLMetadataService.readMetadata.success=1 count,AvailabilityAnalyzer.recordRequestStatus=1 count,LoadShedderProtector.Intercepted=1 count,LoadShedderProtector.Intercepted.UDLMetadataServiceFacade.readMetadata=1 count,LoadShedderProtector.Shed=0 count,LoadShedderProtector.Shed.UDLMetadataServiceFacade.readMetadata=0 count,LoadShedderProtector.Shed.UDLMetadataServiceFacade.readMetadata.NORMAL=0 count,LoadShedderProtector.Allowed=1 count,LoadShedderProtector.UDLMetadataServiceFacade.readMetadata.Success=1 count,LoadShedderProtector.UDLMetadataServiceFacade.readMetadata.Failure=0 count,DigitalAnnotationsService.getAnnotations.success=1 count,AnnotationLoader.retrievedAnnotations=13 entries,FutureSoftwareVersionService.success=1 count,Capabilities.CacheHit=1 occurence,annotation.loader.metadataGuid=1 time,CodigoDigicat.success=1 count,CodigoDigicat.success=1 count,KCMS.getMetadata.success=1 count,KCMS.getManifest.success=1 count,KCMS.Manifest.hit=1 count,GetInstructionAndDescriptor.Success=1 request,cde.mobi.das.bytes=617036 bytes,AnnotationGenerator.LoadFrom.DAS=1 count,MobipocketAnnotationGenerator.LoadFrom.DAS=1 count,GetInstructionAndDescriptor.Success=1 request,cde.mobi.das.bytes=617036 bytes,mobi7generator.quoteFailure=0 time,cde.sidecar.bytes.Mobi7=3350 bytes,cde.sidecar.bytes=3350 bytes
Info=RESTServlet.Get.Sidecar
Details=[currentCountry=IN, device_lto=null, FSN=B006000401130060, CustomerId=AAMPH2HEDEY21, isSecure=true, DeviceType=A1VC38T7YXB528, ASIN=B004IWRH1G, Type=EBOK, guessedContent={{http://internal.amazon.com/Whispersync/Types}ContentReference Contents: [ contentType=EBOK asin=B004IWRH1G version=CR!CZ13Z3CJKD6KHAYRT1TMYBQFC4TH:D3861F6E format=Mobi7 acr=CR!CZ13Z3CJKD6KHAYRT1TMYBQFC4TH ]}, AssetLoader=DASAssetLoader, bytesTransferredFromDAS=617036, AssetLoader=DASAssetLoader, bytesTransferredFromDAS=617036, Mobi7SidecarBytes=3350]
MarketplaceId=ATVPDKIKX0DER
Program=FionaCDEServices
Operation=RESTServlet.Get.Sidecar
EOE




EndTime=Fri Sep 28 07:24:04 UTC 2012
StartTime=1348817042.275
Time=2517 msecs
Hostname=cde-gamma-na-5001.iad5.amazon.com
Timing=KindleMutualAuthenticator.authenticateRequest:121/1,DeviceMasterCacheService.GetRegisteredDeviceAccounts:213/2,DeviceMasterDataLoader.constructor:93/1,DeviceMetadataServiceDataLoader.constructor:30/2,DeviceMetadataService.GetDeviceMetadata:15/1,FionaCDEServiceEngine.Weblab:1/1,SidecarStream.SidecarGenerator:2285/1,SidecarStream.request:2285/1,FutureSoftwareVersionService.getResult:0/1,KindleSidecarGenerator.getSidecar:2285/1,EbokSidecarBuilder.GetSidecar:2285/1,UDLMetadata.call:6/1,UDLMetadataService.readMetadata:6/1,ContentMetadata.call:34/3,AnnotationClient.getAnnotations:1845/1,AnnotationClient.paginatedGetAnnotations:1844/1,DigitalAnnotationsService.getAnnotations:1844/1,EbokSidecarBuilder.FilteringTime:12/1,EbokSidecarBuilder.MappingTime:35/1,PositionMapper.call:32/1,Digicat.call:6/1,DigitalCatalogService.getProduct:6/1,MobiSidecarGenerator.generateSidecar:358/1,KCMS.getManifest:11/1,DASAssetLoader.loadAsset:288/2,DASAssetLoader.getSimpleFileStorage:22/2,GetInstructionAndDescriptor:144/2,GetAsset.InputStream:122/2
Counters=Capabilities.CacheHit=1 occurence,DeviceMasterCacheService.GetRegisteredDeviceAccounts.success=1 count,AuthPool.Amazon=1 times,CertificateType.1=1 times,CustomerIdPresentA1VC38T7YXB528=1 count,DeviceMasterCacheService.GetRegisteredDeviceAccounts.success=1 count,DMCS_FoundAccount=1 occurence,DeviceMetadataService.GetDeviceMetadata.success=1 count,SidecarStream.currentCountryCodeReadFromURL=1 occurence,cde.weblab.SIDECAR_MIGRATION_CDE_14114.T1=1 occurrence,FutureSoftwareVersionService.success=1 count,UDLMetadataService.readMetadata.success=1 count,DigitalAnnotationsService.getAnnotations.success=1 count,AnnotationsCount=6 count,Capabilities.CacheHit=1 occurence,Capabilities.CacheHit=1 occurence,DigitalCatalogService.getProduct.success=1 count,KCMS.getManifest.success=1 count,GetInstructionAndDescriptor.Success=1 request,DASAssetLoader.bytesTransferred=669464 bytes,AnnotationGenerator.LoadFrom.DAS=1 count,MobiSidecarGenerator.LoadFrom.DAS=1 count,GetInstructionAndDescriptor.Success=1 request,DASAssetLoader.bytesTransferred=669464 bytes,AnnotationsInSidecar=6 occurence
Info=RESTServlet.Get.Sidecar
Details=[currentCountry=IN, device_lto=null, Asin=B004TAFNCM, Type=EBOK, DeviceAccountId=A1NAABDWAE4TMA, DSN=B006000401130060, DeviceType=A1VC38T7YXB528, CustomerId=AHP0PPADZCVYQ, DAS.FileName=DTP:0000001137234_efb2915e.azw, DAS.Folder=ebook-content, SidecarContentType=application/x-mobipocket-sidecar, SidecarBytes=1636]
Program=FionaCDEServices
Operation=RESTServlet.Get.Sidecar
EOE
